sudo: required

services:
- docker

language: node_js
node_js:
  - "lts/*"
  - "node"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - yarn run test

jobs:
  include:
  - stage: docker_build
    script: yarn run build:docker
