sudo: required

services:
  - docker

language: node_js

node_js:
  - "lts/*"
  - "node"

script:
  - yarn run test

jobs:
  include:
    - stage: lint
      script: yarn run lint
      node_js: "lts/*"
    - stage: docker_build
      script: yarn run build:docker
      node_js: "lts/*"
